### ISSUE TITLE
Proposal: reorganize media files

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/GPG-Bootcamp#8]
Since we are using numbers for the articles I would suggest putting the article media files inside a subfolder like this:

```
├── media
│   ├── 010
│   │   ├── commit-with-partially-verified-signature-on-github.png
│   │   └── commit-with-verified-signature-on-github.png
```

What do you think @cgbosse?

I think that way would be easier to know which article the media file belongs to and all the media articles belonging to an article. If we have some of them shared between articles we can create a "shared" folder.

I did it that way in my latest [PR](https://github.com/Nautilus-Cyberneering/GPG-Bootcamp/pull/6).

**Comment by cgbosse** [comment]
Sure. Will start changing them.
